default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_dev
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chakaboom_development

test:
  <<: *default
  database: chakaboom_test

production:
  <<: *default
  database: chakaboom_production
  username: chakaboom
  password: <%= ENV['CHAKABOOM_DATABASE_PASSWORD'] %>
